In [33]:
import os
import pandas as pd
import numpy as np
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
#from pandas.

In [22]:
S1PATH = os.path.join('..','..','C:/Users/Mahran/Desktop/Year 3/Machine Learning/ML-Assignment1','S1_Dataset')
S2PATH = os.path.join('..','..','C:/Users/Mahran/Desktop/Year 3/Machine Learning/ML-Assignment1','S2_Dataset')
s1 = pd.DataFrame()
for filename in os.listdir(S1PATH):
    if filename != 'README.txt':
        data_path = os.path.join(S1PATH, filename)
        data=pd.read_csv(data_path, header=None)
        s1= s1.append(data, ignore_index=True)
s1.columns = ['time','frontal','vertical','lateral','id','rssi','phase','frequency','activity']
s1.head()

   time  frontal  vertical   lateral  id  rssi   phase  frequency  activity
0  0.00  0.27203   1.00820 -0.082102   1 -63.5  2.4252     924.25         1
1  0.50  0.27203   1.00820 -0.082102   1 -63.0  4.7369     921.75         1
2  1.50  0.44791   0.91636 -0.013684   1 -63.5  3.0311     923.75         1
3  1.75  0.44791   0.91636 -0.013684   1 -63.0  2.0371     921.25         1
4  2.50  0.34238   0.96229 -0.059296   1 -63.5  5.8920     920.25         1

In [23]:
s1.shape

(52482, 9)

In [24]:
s1.isna().sum()

time         0
frontal      0
vertical     0
lateral      0
id           0
rssi         0
phase        0
frequency    0
activity     0
dtype: int64

In [25]:
s1.describe()

,time,frontal,vertical,lateral,id,rssi,phase,frequency,activity
count,52482.000000,52482.000000,52482.000000,52482.000000,52482.000000,52482.000000,52482.000000,52482.000000,52482.000000
mean,235.001862,0.805042,0.377804,0.007710,2.360752,-58.430814,3.275907,922.762261,2.375996
std,148.256886,0.396362,0.468899,0.180674,1.261542,4.611220,2.240341,1.693769,0.941795
min,0.000000,-0.748080,-0.553490,-0.481210,1.000000,-70.000000,0.000000,920.250000,1.000000
25%,117.980000,0.424460,-0.025263,-0.093505,1.000000,-61.500000,0.951070,921.250000,1.000000
50%,227.665000,0.952100,0.135500,-0.025087,3.000000,-57.500000,4.072700,922.750000,3.000000
75%,325.750000,1.128000,0.916360,0.066138,4.000000,-56.500000,5.425700,924.250000,3.000000
max,730.250000,1.503200,2.030200,1.217800,4.000000,-38.500000,6.281700,925.750000,4.000000

In [31]:
X = s1['lateral'].to_numpy
Y = s1['vertical'].to_numpy
Z = s1['frontal'].to_numpy